const Strings = {

    en: {

        "login": {
            "signIn": "Sign In",
            "userName": "User Name",
            "enterUserName": "Enter user name",
            "password": "Password",
            "enterPassword": "Enter password",
            "rememberMe": "Remember Me",
            "forgotPassword": "Forgot password ?",
            "dontHaveAnAccount": "Don't have an account?",
            "signUp": "Sign Up",
            "thisFieldIsRequired": "This field is required.",
            "invalidUserName": "Invalid user name",
            "invalidPassword": "Enter valid password",
            "english": "English",
            "arabic": "Arabic"
        },
        "header": {
            "login": "Login",
            "smartControl": "SMART CONTROL",
            "welcome": "Welcome",
            "guest": "Guest"
        },
        "dashboard": {
            "myTasks": "My Tasks",
            "licenses": "Licenses",
             "license":"LICENSES",
            "cases": "Cases",
             "case":"CASES",
            "campaign": "Campaign",
            "temporaryPermits": "Temporary Permits",
            "adhocTasks": "Adhoc Tasks",
            "foodAlerts": "Food Alerts",
            "completedTesk": "Completed Task",
            "history": "History / New Task",
            "search": "Search",
            "sort":"Sort By",
            "filter":"Filter By",
            "visibleTask":"Task Visibility",
            "pleaseEnterText": "Please Enter Text"
        },
        "establishmentDetails": {
            "establishmentDetails": "Establishment Details",
            "establishmentName": "Establishment Name",
            "licenseSource": "License Source",
            "licenseStartDate": "License Start Date",
            "licenseEndDate": "License End Date",
            "licenseNumber": "License Number",
            "contactDetails": "Contact Details",
            "address": "Address",
            "area": "Area",
            "contact": "Contact",
            "efst": "EFST",
            "sector": "Sector",
            "print":"Print",
            "printSibleReport":"Print Siebel Report",
            "viewChecklist":"View Checklist",
            "createPdfMsg":"Create PDF",
            "reportThisTask":"Report This Task",
            "updateLocation":"Update Location"
        },
        "alertComponent": {
            "score": "Score",
            "description": "Description",
            "nonComplaince": "Non complaince",
        },
        "inspectionDetails": {
            "finalInspectionReport":"Final Inspection Report",
            "inspectionResult":"Inspection Result",
            "inspectionDetails": "Inspection Details",
            "inspectionDetailsbtn": "Inspection Details",
            "taskId": "Task ID",
            "taskType": "Task Type",
            "creationDate": "Creation Date",
            "businessActivity": "Business Activity",
            "subbusinessActivity": "Sub Business Activity",
            "description": "Description",
            "risk": "Risk",
            "sheduledDate": "Sheduled Date",
            "action": "Action",
            "startInpection": "Start Inspection",
            "inspectionNo": "Inspection No.",
            "acknowledge": 'Acknowledge',
            "mergeTask" :"Merge Task",
            "deleteCheck" :"Delete Checklist",
            "goLive":"Go Live",
            "selectBusinessActivity": "Select Business Activity",
            "details": "Details"
        },
        "historyInspectionDetails": {
            "inspectionDetails": "Inspection Details",
            "inspectionNumber": "Inspection Number",
            "taskType": "Task Type",
            "creationDate": "Creation Date",
            "completionDate":"Completion Date",
            "status": "Status",
            "businessActivity": "Business Activity",
            "grade": "Grade",
            "description": "Description",
            "priority": "Priority",           
            "viewChecklist":"View CheckList"
        },
        "myTask": {
            "myTask": "MY TASKS",
            "inspectionId": "InspectionId",
            "type": "Type",
            "license": "License",
            "searchHere": "Search here"
        },
        "startInspection": {
            "startInpection": "START INSPECTION",
            "part1DesignAndStructureAndEquiment": "Part 1 :Design,Structure and Equiment",
            "updateSomething": "1.update something",
            "contactName": "Contact Name",
            "mobileNumber": "Mobile Number",
            "emiratesId": "Emirates Id",
            "evidence": "Other",
            "license": "License",
            "checklist": " Step 1: Checklist",
            "submission": "Step 3: Submission",
            "documentation": "Step 2: Documentation & Records",
            "checklistSubmittedSuccessfully": "Checklist Submitted Successfully",
            "checklistNotAvailable": "No Checklist",
            "condemnation": "Condemnation",
            "detention": "Detention",
            "sampling": "Sampling",
            "onHoldRequest": "On Hold Request",
            "requestforClosure": "Request for Closure",
            "finalResult": "Final Result",
            "finalInspectionResult": "Final Inspection Result",
            "totalScore": "Total Score",
            "grade": "Grade",
            "percentage": "Percentage",
            "calculate": "Calculate",
            "print": "Print",
            next: 'Next',
            back: 'Back',
            thermometer: 'Thermometer',
            flashLight: 'Flash Light',
            uvLight: 'UV Light',
            luxMeter: 'Lux Meter',
            dataLogger: 'Data Logger',
            visitType: 'Visit Type',
            scope: 'Scope',
            noOfVisits: 'No. Of Inspections Visits',
            add: 'Add',
            parano:"Para No.",
            question:"Question",
            score:"Score",
            comments:"Comments",
            grace:"Grace"
        },
	"documentAndRecord":{
            signHere:"Please Sign Here",
            save:"Save",
            result:"Result",
            finalComment:"Final Comment",
            condemnation:"Condemnation",
            sampling:"Sampling",
            detention:"Detention",
            onHoldRequest:"On Hold Request",
            requestForClosure:"Request for Closure",
        },
        "contactList": {
            "contactList": "CONTACT LIST",
            "type": "Type",
            "name": "Name",
            "nationality": "Nationality",
            "mobileNumber": "Mobile Number",
            "relationship": "Relationship",
        },
        "action": {
            "action": "ACTION",
            "taskId": "Task ID",
            "establishment": "Establishment",
            "reason": "Reason",
            "comments": "Comments",
            "proposedDate": "Proposed Date",
            "submit": "Submit",
            "cancel": "Cancel",
            "submitWC": "Submit Without Checklist",
        },
        "efstDetails": {
            "efstDetails": "EFST DETAILS",
            "foodHandlerId": "Food Handler ID",
            "emiratesId": "Emirates ID",
            "foodHandlerName": "Food Handler Name",
            "gender": "Gender",
            "passPercentage": "Pass Percentage",
            "nationality": "Nationality",
            "passortNumber": "Passort Number",
            "trained": "Trained",
            "certified": "Certified",
            "foodHandlerCount": "Food Handler Count",
            "noUpdates": "No Updates",
            "update": "Update",
        },
        "profile": {
            "profileDetails": "Profile Details",
            "guideManual": "Manuals/Guides",
            "inspectorName": "Inspector Name",
            "position": "Position",
            "inspectionArea": "Inspection Area",
            "unit": "Unit",
            "selectLanguage": "Select Language",
            "fileType": "File Type",
            "manualName": "Manual Name",
            "versionNumber": "Version Number"
        },
        "taskList": {
            "document": "Document",
            "staff": "Staff",
            "lastReport": "Last Report",
            "history": 'History',
            "directions": "Directions",
            "routineInspection": "Routine Inspection",
            "followUp": "FollowUp",
            "complaints": "Complaints",
            "license": "License",
            "foodAlerts": "FoodAlerts",
            "instantViolation": "Instant Violation",
            "adhocTasks": "Adhoc Task",
            "sampling": "Sampling",
            "condemnation": "Condemnation",
            "detention": "Detention",
            "closure": "Closure",
            "scheduled": "Scheduled",
            "adhoc": "Adhoc",
            about: "About",
            document: "Documents"
        },
        "detention": {
            "detention": "Detention",
            "condemnation": 'Condemnation',
            "recordNumber": 'Record No ',
            "serialNumber": "Serial Number",
            "productName": "Product Name",
            "brandName": "Brand Name",
            "addRecord": "Add Record",
            "finalSubmit": "Final Submit",
        },
        "sampling": {
            "sampling": "Sampling",
            msgS1: 'Please Click On Sampling and do Sampling for Food Alert Number',
            msg2: 'Product Name',
            msg3: 'Batch Number',
            msgS4: 'Do You want to do this Sampling inspection.',
            msgC1: 'Please Click On Condemnation and do Condemnation for Food Alert Number',
            msgC4: 'Please do this Condemnation inspection.',
            msgD1: 'Please Click On Detention and do Detention for Food Alert Number',
            msgSamplingFirst: 'Please do Sampling first for Food Alert Number',
            msgCondemnationFirst: 'Please do Condemnation first for Food Alert Number',
            msgSamplingDetentionFirst: 'Please do Sampling and Condemnation first for Food Alert Number',
            msgD4: 'Please do this Detention inspection.'
        },
        "foodAlert": {
            "foodAlert": "Food Alerts",
            "title": "Food Alerts History",
            "alertId": "Alert Id#",
            "type": "Type",
            sayNoToAll: 'Say No To All'
        },
        "reminder": {
            "reminder": "Reminder",
        },
        "completedTasks": {
            completedTasks: "Completed Tasks",
            all:"All",
            failed:"Failed",
            queued:"Queued",
            allTask: 'All Task',
            failedTask: 'Failed Task',
            date: 'Date',
            "pdfCreated":"PDF created Successfully"
        },
        "settings": {
            "settings": "Settings",
            "inspectorName":"Inspector Name",
            "position":"Position",
            "inspectionArea":'Inspection Area',
            "unit":'Unit',
            "selectLanguage":'Select Language',
            "save":'Save',
            "cancel":"Cancel",
            "oldPassword":"Old Password",
            "newPassword":'New Password',
            "retypePassword":"Retype Password",
            "editUserProfile":"Edit User Profile",
            "changePassword":"Change Password",
            "notification":'Notification',
            "logOut":"Log Out",
            "reloadlov":"Reload LOV",
            "reloadEst":"Reload Establishment"
        },
        "bottomText": {
            "profile": "Profile",
            "tasks": "Tasks",
            "category": "Category",
            "home": "Home",
            "foodAlerts": "Food Alerts",
            "maps": "Map",
            "completedTasks": "Completed Tasks",
            "settings": "Settings"
        },
        "condemnationForm": {
            title: "INPUT FOR CONDEMNATION",
            serialNumber: "Serial Number",
            productName: "Product Name",
            unit: "Unit",
            quantity: "Quantity",
            netWeight: "Net Weight/Net Value",
            package: "Package",
            batchNumber: "Batch Number",
            brandName: "Brand Name",
            remarks: "Remarks",
            place: "Place",
            reason: "Reason",
            attachments: "Attachments",
            submit: "Submit",
            cancel: "Cancel",
            reject: "Reject",
            "afterDeduction":"After Deduction :",
            "beforeDeduction":"Before Deduction :",
            "submitScore": "Submit Score",
            ok: 'Ok',
            edit:"Edit"
        },
        "samplingForm": {
            title: "Input for sampling",
            serialNumber: "Serial Number",
            sampleCollectionReason: "Sample Collection Reason",
            sampleName: "Sample Name",
            sampleDateCollectionName: "Date of Sample Collection",
            sampleStatusCollected: "Sample status when Collected",
            sampleTemp: "Sample Temperature(°C)",
            type: "Type",
            unit: "Unit",
            quantity: "Quantity",
            netWeight: "Net Weight/Net Value",
            package: "Package",
            batchNumber: "Batch Number",
            brandName: "Brand Name",
            productionDate: "Production Date",
            expiryDate: "Expiry Date",
            countryOrigin: "Country of Origin",
            remainingQuantities: "Remaining Quantities",
            remarks: "Remarks",
            attachments: "Attachments",
            submit: "Submit",
            typeOfAnalysis: "Type Of Analysis",
            cancel: "Cancel"
        },
        "detentionForm": {
            title: "INPUT FOR DETENTION",
            serialNumber: "Serial Number",
            type: "Type",
            unit: "Unit",
            quantity: "Quantity",
            netWeight: "Net Weight/Net Value",
            package: "Package",
            batchNumber: "Batch Number",
            brandName: "Brand Name",
            selectDate: "Select Date",
            productionDate: "Production Date",
            reason: "Reason for Detention",
            decisions: "Decisions",
            attachments: "Attachments",
            submit: "Submit",
            cancel: "Cancel",
            termsAndCondition: "I accept Terms and Conditions",
            clickToView: "Click Here to View"
        },
        "onHoldRequest": {
            onHoldRequestDetails: 'On Hold Request Details',
            inspectionId: 'Inspection ID',
            type: 'Type',
            createdBy: 'Created By',
            establishment: 'Establishments',
            reason: 'Reason',
            comments: 'Comments',
            submit: "Submit",
            cancel: "Cancel"
        },
        "requestForClosure": {
            requestForClosureDetails: 'Request for Closure details',
            inspectionId: 'Inspection ID',
            type: 'Type',
            createdBy: 'Created By',
            establishment: 'Establishments',
            reason: 'Reason',
            comments: 'Comments',
            submit: "Submit",
            cancel: "Cancel"
        },
        "foodAlerts": {
            foodAlerts: "FOOD ALERTS",
            alertNumber: "Alert Number",
            foodAlertDetails: "Food Alert Details",
            viewProductList: "View Product List",
            alertType: "Alert Type",
            alertSource: "Alert Source",
            status: "Status",
            startDate: "Start Date",
            toDate: "To Date",
            description: "Description",
            sourceAlertNumber: "Source Alert Number",
            productName: "Product Name :",
            actiontaken: "Action to be taken",
            brand: "Brand",
            type: "Type",
            batch: "Batch",
            quantity: "Quantity",
            weight: "Weight",
            unit: "Unit",
            country: "Country",
            foodAlertHistory: "Food Alert History",
            viewAttachments: "View Attachments",
            printHistory: "Print History",
            productList: "Product List",
            attachment: "Attachments",
            currentEstablishments: 'Is this Alert Applicable to current Establishments?',
            productInfo: 'Product Info',
            comments: 'Comments',
        },
        "LastRecord": {
            lastRecord: 'Last Report',
            statics: 'Statics',
            statusPieChart: 'Status Pie Chart',
            satisfactory: 'Satisfactory',
            unsatisfactory: 'Unsatisfactory',
            done: 'Done',
            about: 'About',
            taskType:'Task Type',
            creationDate:'Creation Date',
            score:'Score',
            grade:'Grade',
            action:'Action',
            businessActivity:'Business Activity',
            status:'Status',
            actualInspectionDate:'Actual Inspection Date',
            inspectionDetails:'Inspection Details',
        },
	"documentAndRecord": {
            save: 'Save',
            result: 'Result',
            finalComment: 'Final Comments',
            signHere: 'Sign Here'
        },
        "staff": {
            name: 'Name',
            contact: 'Contact',
            post: 'Post'
        },
        history: {
            stopSync: 'Stop Sync',
            reportTask: 'Report Task',
            printReport: 'Print Report',
            viewChecklist: 'View Checklist',
             "history":"HISTORY",
            "serachByEstablishment":"Search by Establishment",
            "searchByVehicle":"Search By Vehicle",
            "serviceRequest":"Service Request",
            "violation":"Violation",
            "vehicleDetails":"Vehicle Details",
            "efst":"EFST",
            "inspection":"Inspection"
        },
        "violationDetails": {
            "adhoc": "ADHOC",
            "violationList": "Violation List",
            "violationID": "Violation ID#",
            "inspectionID": "Inspection ID#",
            "status": "Status",
            "violationDetails": "Violation Details",
            "violationNumber": "Violation Number",
            "inspectionNumber": "Inspection Number",
            "createdBy": "Created By",
            "creationDate": "Creation Date",
            "status": "Status",
            "submit": "Submit",
            "cancel": "Cancel"
        },
        "scheduled": {
            "scheduled": "SCHEDULED",
            "complaints": "Complaints",
            "routineInspection": "ROUTINE INSPECTION",
            "license": "LICENSE",
            "followUp": "FOLLOW UP"
        },
               
        temporaryPermits: {
            alertTitle: 'Do you wish to perform an existing inspection or create new AdHoc Inspection ??',
            performExisting: 'Perform Existing',
            createAdhoc: 'Create Adhoc',
            serviceRequestList: 'Service Request List',
            showSr: 'Show Sr',
            tradeLicenseNumb: 'Trade License Number',
            licenseExpiryDate: 'License Expiry Date',
            mainBA: 'Main Business Activity',
            sector: 'Sector',
            custName: 'Customer Name',
            estType: 'Establishment Type',
            licenseSource: 'License Source',
            area: 'Area',
            serviceReqNum: 'Service Request Number',
            application: 'Application',
            applicationType: 'Application Type',
            closedDate: 'Closed Date',
            permitStartDate: 'Permit Start Date',
            permitEndDate: 'Permit End Date',
            city: 'City',
            requestNo:'Request No',
            certificateNo:'Certificate Number',
            certificatestartDate:'Certificate Start Date',
            certificateExpiryDate:'Certificate Expiry Date',
            noOfBooth:'Number of Booths',
            eventName:'Event Name',
            location:'Location',
            eventType:'Event Type',
            premiseAddress:'Premise Address',
            assignTo:'Assigned To'
        },
         "adhocTask":{
            "adhocTask":"ADHOC TASKS",
            "establishment":"Establishment",
            "englishTradeName":"English Trade Name",
            "arabicTradeName":"Arabic Trade Name",
            "licenseSource":"License Source",
            "licenseNo":"License No.",
            "area":"Area",
            "sector":"Sector",
            "search":'Search',
            "createTask":"Create Task",
            "createNew":"Create New",
            "vehicle":"Vehicle",
            "placeofIssue":"Place of Issue",
            "plateNumber":"Plate Number",
            "plateCode":"Plate Code",
            "chassisNumber":"Chassis Number",
            "cancel":"Cancel",
            "establishmentName":"Establishment Name",
            "tradeLicense":"Trade License",
            "licenseSource":"License Source",
            "address":"Address",
            "establishmentDetails":"Establishment Details",
            "licenseNumber":"License Number",
            "licenseStartDate":"License Start Date",
            "licenseEndDate":"License End Date",
            "arabicEstablishmentName":"Arabic Establishment Name",
            "contactDetails":"Contact Details",
            "emailid":"Email ID",
            "onHold":"On Hold",
            "businessActivity":"Business Activity",
            "selectVehicle":"Select Vehicle",
            "taskType":"Task Type",
            "selectBazar":"Select Bazar",
            "createNewTask":"Create New Task",
            "createAndView":"Create and View",
            "establishmentEngName":"Establishment English Name",
            "establishmentArName":"Establishment Arabic Name",
            "establishmentType":"Establishment Type",
            "establishmentClass":"Establishment Class",
            "plateCode":"Plate Code",
            "plateNumber":"Plate Number",
            "vehicleMake":"Vehicle Make",
            "contact":"Contact",
            "tradeLicenseNumber":"Trade License Number",
            "tradeLicenseSource":"Trade License Source",
            "createNewEstablishment":"Create New Establishment",
            "bussinessActivitynotfound":"No associated bussiness activity found",          
            "selectTaskType":"Select TaskType"          
        },
        "serviceRequstList":{
            "serviceRequestList":"Service Request List",
            "serviceRequestNo":"Service Request No",
            "applicationType":"Application Type",
            "application":"Application", 
            "serviceRequestDetails":"Service Request Details",
            "serviceRequestNo":"Service Request No", 
            "city":"City",
            "status":"Status",
            "creationDate":"Creation Date",
            "closedDate":"Closed Date",
            "permitsStartDate":"Permit Start Date",
            "permitEndDate":"Permit End Date",
            "businessActivity":"Business Activity",
            "category":"Category", 
            "violationList":"Violation List",
            "violationNumber":"Violation Number",
            "inspectionNumber":"Inspection Number",
            "violationDetail":"Violation Details",
            "createdBy":"Created By",              
        },     

        "vehicleDetails":{
            "vehicleDetails":"Vehicle Details",
            "plateCode":"Plate Code",
            "plateNumber":"Plate Number",
            "placeOfIssue":"Place Of Issue"
        },
	"closureInspection":{
            "title": "Closure Inspection",
            "tradeName":"Trade Name",
            "licenseNo":"License No",
            "nameoffoodbusinessoperator":"Name of Food Business Operator",
            "signatureOfFood":"Signature of Food Business Operator",
            "address":"Address",
            "comment":"Comment",
            "inspectorName":"Inspector Name",
            "submit":"Submit",
            "msg":"Is this Inspection Approved?",
            "yes":"Yes",
            "no":"No"
        },
        "campaignDetails": {
            "planNumber": "Plan Number",
            "comments": "Comments",
             "planStartDate":"Plan Start Date",
            "expectedCompletionDate": "Expected Completion Date",
             "CompletionDate":"Completion Date",
            "priority": "Priority",
            "Description": "Decription",
            "startCampaign": "Start Campaign",
            "campaignPlanDetails": "Campaign Plan Details",
            "listOfEstablishment": "List Of Establishments",
            "campaign":"CAMPAIGN",
            "campaignInspection" : "Campaign Inspection",
              "view" : "View"
        },
    },

    ar: {

        "login": {
            "signIn": "تسجيل الدخول",
            "userName": "اسم المستخدم",
            "enterUserName": "ادخل اسم المستخدم",
            "password": "كلمه السر",
            "enterPassword": "أدخل كلمة المرور",
            "rememberMe": "تذكرنى",
            "forgotPassword": "هل نسيت كلمة المرور ؟",
            "dontHaveAnAccount": "ليس لديك حساب؟ ",
            "signUp": "تسجيل",
            "thisFieldIsRequired": "هذه الخانة مطلوبه.",
            "invalidUserName": "اسم المستخدم غير صحيح",
            "invalidPassword": " كلمة المرور غير صحيحة",
            "english": "الإنجلزية",
            "arabic": "العربية"
        },
        "header": {
            "login": "دخول",
            "smartControl": "برنامج التفتيش الذكي",
            "welcome": " أهلا وسهلا بك",
            "guest": "زائر"
        },
        "dashboard": {
            "myTasks": "قائمة مهامي",
            "licenses": "طلبات الخدمة",
            "cases": "الحالات",
            "campaign": "حملات",
            "temporaryPermits": "التصاريح مؤقتة",
            "adhocTasks": "المهام اضافية",
            "foodAlerts": "الإخطارات الغذائية",
            "completedTesk": "المهام المنجزة",
            "history": "السجل",
            "search": "بحث",
            "sort":"فرز",
            "filter":"الاختيار",
            "visibleTask":"مشاهدة المهمة",
            "pleaseEnterText": "الرجاء إدخال الكلمة"
        },
        "establishmentDetails": {
            "establishmentDetails": "بيانات المنشأة",
            "establishmentName": "اسم المنشأة",
            "licenseSource": "مصدر الرخصة",
            "licenseStartDate": "تاريخ تسجيل الرخصة ",
            "licenseEndDate": "تاريخ انتهاء الرخصة ",
            "licenseNumber": "رقم الرخصة",
            "contactDetails": "بيانات التواصل",
            "address": "العنوان",
            "area": "المنطقة الرئيسية",
            "contact": "ارقام التواصل",
            "efst": "بيانات التدريب",
            "sector": "المنطقة الفرعية",
            "print":"طباعة",
            "printSibleReport":"طباعة التقرير من برنامج المعاملات",
            "viewChecklist":"عرض القائمة التفقدية",
            "createPdfMsg":"إنشاء ملف بصيغة البي دي ايف",
            "reportThisTask":"الإبلاغ عن هذه المهمة",
            "updateLocation":"تحديث الموقع"
        },
        "alertComponent": {
            "score": "الدرجة",
            "description": "وصف",
            "nonComplaince": "عدم المطابقة",
        },
          "historyInspectionDetails": {
            "inspectionDetails": "تفاصيل التفتيش",
            "inspectionNumber": "رقم التفتيش",
            "taskType": "نوع المهمة",
            "creationDate": "تاريخ الإنشاء",
            "completionDate":"تاريخ الإنجاز",
            "status": "الحالة",
            "businessActivity": "النشاط التجاري",
            "grade": "الدرجة",
            "description": "وصف",
            "priority": "الأولويات",           
            "viewChecklist":"عرض القائمة التفقدية"
        },
        "inspectionDetails": {
            "inspectionDetails": "تفاصيل التفتيش",
            "inspectionDetailsbtn": "تفاصيل التفتيش",
            "taskId": "رقم المهمة",
            "taskType": "نوع المهمة",
            "creationDate": "تاريخ الإنشاء",

            "businessActivity": "النشاط الرئيسي ",
            "subbusinessActivity": "النشاط الفرعي",
            "description": "وصف",
            "risk": "درجة الخطورة",
            "sheduledDate": "تاريخ الزيارة المجدولة",
            "action": "الإجراء",
            "startInpection": "البدء بالتفتيش",
            "inspectionNo": "رقم المهمة",
            "acknowledge": 'مستلمة',
            "goLive":"التفتيش عن بعد",
            "mergeTask" :"Merge Task",
            "deleteCheck" :"Delete Checklist",
            "submitWC": "إرسال بدون قائمة التفتيش ",
            "selectBusinessActivity": "حدد نشاط العمل",
            "details": "تفاصيل"
        },
        "myTask": {
            "myTask": "قائمة مهامي",
            "inspectionId": "التفتيش",
            "type": "نوع",
            "license": "رقم الرخصة",
            "searchHere": "ابحث هنا"
        },
        "startInspection": {
            "startInpection": "البدء بالتفتيش",
            "part1DesignAndStructureAndEquiment": "الجزء 1: التصميم والهيكل والمعدات",
            "updateSomething": "1. القيام بالتحديث",
            "contactName": "اسم المتعامل",
            "mobileNumber": "رقم الهاتف ",
            "emiratesId": "رقم الهوية",
            "other": "آخرى",
            "license": "الرخصة التجارية",
            "checklist": " الخطوة 1: قائمة التحقق",
            "submission": "الخطوة 3: التقديم",
            "documentation": "الخطوة الثانية: التوثيق والسجلات",
            "checklistSubmittedSuccessfully": "تم إرسال قائمة التفتيش بنجاح",
            "checklistNotAvailable": "لاتوجد قائمة  تفقدية",
            "condemnation": "اتلاف",
            "detention": "حجز",
            "sampling": "عينات",
            "onHoldRequest": "طلب تعليق",
            "requestforClosure": "طلب اغلاق",
            "finalResult": "النتيجة النهائية",
            "finalInspectionResult": "نتيجة التفتيش النهائية",
            "totalScore": "مجموع النقاط",
            "grade": "الدرجة",
            "percentage": "النسبة المئوية",
            "calculate": "طريقة الإحتساب",
            "print": "طباعة",
            next: 'التالي',
            back: 'الرجوع للخلف',
            thermometer: 'ميزان الحرارة',
            flashLight: 'ضوء الفلاش',
            uvLight: 'ضوء الأشعة فوق البنفسجية  ',
            luxMeter: 'مقياس الإضاءة',
            dataLogger: 'مسجل درجات الحرارة',
            visitType: 'نوع الزيارة',
            scope: 'المجال',
            noOfVisits: 'عدد زيارت التفتيش',
            add: 'اضافة',
            parano:"Para No.",
            question:"Question",
            score:"Score",
            comments:"Comments",
            grace:"Grace"
        },
	"documentAndRecord":{
            signHere:"من فضلك وقع هنا.",
            save:"حفظ",
            result:" نتيجة التفتيش النهائية",
            finalComment:"الملاحظة النهائية",
            condemnation:"اتلاف",
            sampling:"عينات",
            detention:"حجز",
            onHoldRequest:"طلب تعليق",
            requestForClosure:"طلب اغلاق",
        },
        "contactList": {
            "contactList": "قائمة الإتصال",
            "type": "نوع",
            "name": "اسم",
            "nationality": "الجنسية",
            "mobileNumber": "رقم الهاتف المحمول",
            "relationship": "الصلة/العلاقة",
        },
        "action": {
            "action": "الإجراء",
            "taskId": "رقم المهمة",
            "establishment": "اسم المنشأة",
            "reason": "السبب",
            "comments": "الملاحظات",
            "proposedDate": "التاريخ المقترح",
            "submitWC": "إرسال بدون قائمة التفتيش",
            "submit": "إرسال",
            "cancel": "إلغاء"
        },
        "efstDetails": {
            "efstDetails": "بيانات التدريب",
            "foodHandlerId": "رقم هوية متعامل الغذاء",
            "emiratesId": "رقم الهوية",
            "foodHandlerName": "اسم متعامل الغذاء",
            "gender": "الجنس",
            "passPercentage": "نسبة النجاح",
            "nationality": "الجنسية",
            "passortNumber": "رقم جواز السفر",
            "trained": "متدربين",
            "certified": "الحاصلين على الشهادات",
            "foodHandlerCount": "عدد متداولي الغذاء",
            "noUpdates": "لا توجد تحديثات",
            "update": "تحديث",
        },
        "profile": {
            "profileDetails": "تفاصيل الملف الشخصي",
            "guideManual": "كتيبات / أدلة",
            "inspectorName": "اسم المفتش",
            "position": "الوظيفة",
            "inspectionArea": "مناطق التفتيش",
            "unit": "وحدة",
            "selectLanguage": "اللغة المختارة",
            "fileType": "نوع الملف",
            "manualName": "الاسم ",
            "versionNumber": "رقم الإصدار"
        },
        "taskList": {
            "document": "وثيقة",
            "staff": "العاملين",
            "lastReport": "آخر تقرير",
            "history": 'السجل',
            "directions": "الاتجاهات",
            "routineInspection": "تفتيش روتيني",
            "followUp": "متابعة",
            "complaints": "شكاوي",
            "license": "رخصة",
            "foodAlerts": "الإخطارات الغذائية",
            "instantViolation": "مخالفة فورية",
            "adhocTasks": "مهمة مخصصة",
            "sampling": "العينات",
            "condemnation": "إتلاف",
            "detention": "الحجز",
            "closure": "إغلاق",
            "scheduled": "مجدولة",
            "adhoc": "مهام اضافية",
            about: "حول",
            document: "مستندات"
        },
        "detention": {
            "detention": "الحجز",
            "condemnation": 'إتلاف',
            "serialNumber": "رقم التسلسلي",
            "recordNumber": "رقم السجل ",
            "productName": "اسم المنتج",
            "brandName": "اسم العلامة التجارية",
            "finalSubmit": "إرسال نهائي",
            "addRecord": "إضافة سجل",
        },
        "sampling": {
            "sampling": "أخذ العينات",
            msgS1: 'الرجاء اختيار اجراء جمع عينات للإخطار الغذائي رقم  ',
            msg2: 'اسم المنتج',
            msg3: 'رقم التشغيلية',
            msgS4: 'هل سيتم جمع عينات',
            msgC1: 'الرجاء اختيار اجراء إتلاف للإخطار الغذائي رقم',
            msgC4: 'هل تريد القيام بإجراء إتلاف .',
            msgD1: 'الرجاء اختيار اجراء حجز للإخطار الغذائي رقم',
            msgSamplingFirst: 'الرجاء جمع عينات أولا للإخطار الغذائي رقم ',
            msgCondemnationFirst: 'الرجاء إتلاف المنتجات أولا للإخطار الغذائي رقم',
            msgSamplingDetentionFirst: 'الرجاء القيام بجمع العينات وإتلاف المنتجات أولا للإخطار الغذائي رقم',
            msgD4: ' هل تريد القيام بإجراء حجز للمنتجات الغذائية .'
        },
        "foodAlert": {
            "foodAlert": "إخطار غذائي",
            "title": "عنوان",
            "alertId": "رقم الإخطار #",
            "type": "نوع",
            sayNoToAll: 'لم يتم العثور على جميع المنتجات'
        },
        "reminder": {
            "reminder": "تذكير",
        },
        "completedTasks": {
            completedTasks: "المهام المنجزة",
            all: 'جميع المهام',
            failed: 'فشل بالإرسال',
            date: 'تاريخ',
            queued:"قيد الإرسال",
            "pdfCreated":"تم إنشاء ملف بصغية بي دي اف بنجاح"
        },
        "settings": {
            "settings": "الإعدادات",
            "inspectorName":"اسم المفتش",
            "position":"الوظيفة",
            "inspectionArea":'مناطق التفتيش',
            "unit":'وحدة',
            "selectLanguage":'اللغة المختارة',
            "save":'حفظ',
            "cancel":"إلغاء",
            "oldPassword":"كلمة المرور القديمة",
            "newPassword":'كلمة مرور جديدة',
            "retypePassword":"أعد إدخال كلمة السر",
            "editUserProfile":"تعديل كلمة السر ",
            "changePassword":"تغيير كلمة المرور",
            "notification":'تنبيه',
            "logOut":"تسجيل خروج",
            "reloadlov":"إعادة تحميل LOV",
            "reloadEst":"إعادة تحميل المؤسسة"
        },
        "bottomText": {
            "profile": "الملف",
            "tasks": "مهام",
            "category": "الفئة",
            "home": "الصفحة الرئيسية",
            "foodAlerts": "إخطار غذائي",
            "maps": "الخريطة",
            "completedTasks": "المهام المنجزة",
            "settings": "الإعدادات"
        },
        "condemnationForm": {
            "title": "مدخلات الإدانة",
            "serialNumber": "رقم سري",
            "productName": "اسم المنتج",
            "unit": "وحدة",
            "quantity": "كمية",
            "netWeight": "الوزن الصافي / صافي القيمة",
            "package": "صفقة",
            "batchNumber": "رقم التشغيلة",
            "brandName": "اسم العلامة التجارية",
            "remarks": "ملاحظات",
            "place": "مكان",
            "reason": "السبب",
            "attachments": "المرفقات",
            "submit": "إرسال",
            "cancel": "إلغاء",
            reject: "رفض",
            "submitScore": "إرسال النتيجة",
            "afterDeduction":"بعد خصم :",
            "beforeDeduction":"قبل خصم :",
            ok: 'اعتماد',
            edit:"Edit"
        },
        "samplingForm": {
            title: "بيانات العينات",
            serialNumber: "الرقم التسلسلي",
            sampleCollectionReason: "سبب جمع العينة",
            sampleName: "اسم العينة",
            sampleDateCollectionName: "تاريخ جمع العينة",
            sampleStatusCollected: "حالة العينة عند جمعها",
            sampleTemp: "درجة حرارة العينة ",
            type: "نوع",
            unit: "وحدة القياس",
            quantity: "الكمية",
            netWeight: "الوزن",
            package: "نوع التغليف",
            batchNumber: "رقم التشغيلة",
            brandName: "العلامة التجارية",
            productionDate: "تاريخ الانتاج",
            expiryDate: "تاريخ الانتهاء",
            countryOrigin: "بلد المنشأ",
            remainingQuantities: "الكميات المتبقية",
            remarks: "ملاحظات",
            attachments: "المرفقات",
            typeOfAnalysis: "نوع التحليل",
            submit: "إرسال",
            cancel: "إلغاء"
        },
        "detentionForm": {
            "title": "بيانات الحجز",
            "serialNumber": "الرقم التسلسلي",
            "type": "نوع",
            "unit": " وحدة القياس",
            "quantity": "كمية",
            "netWeight": "الوزن الصافي / صافي القيمة",
            "package": "نوع التغليف",
            "batchNumber": "رقم التشغيلة",
            "brandName": "اسم العلامة التجارية",
            "selectDate": "اختيار",
            "reason": "سبب الحجز",
            "productionDate": "تاريخ الإنتاج",
            "decisions": "القرار",
            "attachments": "المرفقات",
            "submit": "إرسال",
            "cancel": "إلغاء",
            "termsAndCondition": "أنا أوافق على الأحكام و الشروط",
            "clickToView": "اضغط للعرض"
        },
        "onHoldRequest": {
            onHoldRequestDetails: 'بيانات طلب التعليق',
            inspectionId: 'رقم مهمة التفتيش',
            type: 'النوع',
            createdBy: 'تم الإنشاء من قبل',
            establishment: 'اسم المنشأة',
            reason: 'السبب',
            comments: 'الملاحظات',
            submit: "إرسال",
            cancel: "إلغاء"
        },
        "requestForClosure": {
            requestForClosureDetails: 'بيانات طلب الإغلاق',
            inspectionId: 'رقم مهمة التفتيش',
            type: 'نوع',
            createdBy: 'تم الإنشاء من قبل',
            establishment: 'اسم المنشأة',
            reason: 'السبب',
            comments: 'الملاحظات',
            submit: "إرسال",
            cancel: "إلغاء"
        },
        "foodAlerts": {
            foodAlerts: "الإخطار الغذائي",
            alertNumber: "رقم الإخطار",
            foodAlertDetails: "تفاصيل الإخطار الغذائي",
            viewProductList: "عرض قائمة المنتجات",
            alertType: "نوع الإخطار",
            alertSource: "مصدر الإخطار",
            status: "الحالة",
            startDate: "تاريخ البدء",
            toDate: "حتى الآن",
            description: "وصف",
            sourceAlertNumber: "رقم مصدر الإخطار",
            productName: "اسم المنتج",
            actiontaken: "Action to be taken",
            brand: "اسم العلامة التجارية",
            type: "نوع",
            batch: "دفعة",
            quantity: "كمية",
            weight: "وزن",
            unit: "وحدة",
            country: "بلد",
            foodAlertHistory: "تاريخ الإخطارالغذاء",
            viewAttachments: "عرض المرفقات",
            printHistory: "تاريخ الطباعة",
            productList: "قائمة المنتجات",
            attachment: "المرفق",
            currentEstablishments: 'هل ينطبق هذا الإخطار على المنشأة الحالية ؟',
            productInfo: 'معلومات المنتج',
            comments: 'الملاحظات'
        },
        "LastRecord": {
            lastRecord: 'التقرير السابق',
            statics: 'إحصائي',
            statusPieChart:'الرسوم الإحصائي للحالات',
            satisfactory: 'مستوفي',
            unsatisfactory: 'غير مستوفي',
            done: 'تم الإنتهاء',
            about: 'حول',
            taskType:'نوع المهمة',
            creationDate:'إنشاء تاريخ ',
            score:'الدرجة',
            grade:'الدرجة',
            action:'الإجراء',
            businessActivity:'النشاط الغذائي',
            status:'الحالات',
            actualInspectionDate:'تاريخ الزيارة المنفذة',
            inspectionDetails:'تفاصيل الزيارة',
        },
        "staff": {
            name: 'اسم',
            contact: 'اتصل',
            post: 'بريد'
        },
        history: {
            stopSync: 'أوقف المزامنة',
            reportTask: 'تقرير المهمة',
            printReport: 'اطبع تقرير',
            viewChecklist: 'عرض قائمة التحقق',
             "history":"التاريخ",
            "serachByEstablishment":"البحث عن طريق اسم المنشأة",
            "searchByVehicle":"البحث عن طريق رقم السيارة",
            "serviceRequest":"طلب خدمة",
            "violation":"المخالفات",
            "vehicleDetails":"تفاصيل السيارة",
            "efst":"بيانات التدريب",
            "inspection":"الزيارات السابقة"          
        },
        "violationDetails": {
            "adhoc": "مخصصة",
            "violationList": "قائمة المخالفات",
            "violationID": "معرف المخالفة #",
            "inspectionID": "معرف التفتيش #",
            "status": "الحالة",
            "violationDetails": "تفاصيل المخالفة",
            "violationNumber": "رقم المخالفة",
            "inspectionNumber": "رقم التفتيش",
            "createdBy": "انشأ من قبل",
            "creationDate": "تاريخ الإنشاء",
            "status": "الحالة",
            "submit": "إرسال",
            "cancel": "إلغاء"
        },
        "scheduled": {
            "scheduled": "الجدولة",
            "complaints": "شكاوي",
            "routineInspection": "تفتيش روتينية",
            "license": "رخصة",
            "followUp": "متابعة"
        },
        temporaryPermits: {
            alertTitle: '  هل سيتم التفتيش على قائمة المنشآت المتواجدة أو يتم إنشاء مهمة جديدة',
            performExisting: 'منشآت متوفرة',
            createAdhoc: 'إنشاء مهمة جديدة (فعالية)',
            serviceRequestList: 'قائمة طلبات الخدمة',
            showSr: 'عرض طلبات الخدمة',
            tradeLicenseNumb: 'رقم الرخصة التجارية',
            licenseExpiryDate: 'تاريخ إنتهاء الرخصة التجارية',
            mainBA: 'النشاط الغذائي الرئيسي ',
            sector: 'قطاع',
            custName: 'اسم المتعامل',
            estType: 'نوع المنشأة',
            licenseSource: 'مصدر الرخصة التجارية',
            area: 'المنطقة',
            serviceReqNum: 'رقم طلب الخدمة',
            application: 'الطلب',
            applicationType: 'نوع الطلب',
            closedDate: 'تاريخ الإغلاق',
            permitStartDate: 'تاريخ بداية الفعالية',
            permitEndDate: 'تاريخ إنتهاء الفعالية',
            city: 'المدينة',
            requestNo:'رقم الطلب',
            certificateNo:'رقم الشهادة',
            certificatestartDate:'تاريخ بدء الشهادة ',
            certificateExpiryDate:'تاريخ إنتهاء الشهادة',
            noOfBooth:'رقم الكشك',
            eventName:'اسم الفعالية',
            location:'الموقع',
            eventType:'نوع الفعالية',
            premiseAddress:'عنوان المنشأه',
            assignTo:'مخصصة إلي'
        },
         "adhocTask":{
            "adhocTask":"المهام الإضافية",
            "establishment":"المنشأة",
            "englishTradeName":"الاسم التجاري باللغة الإنجليزية",
            "arabicTradeName":"الاسم باللغة العربية",
            "licenseSource":"مصدر الترخيص",
            "licenseNo":"رقم الرخصة.",
            "area":"منطقة",
            "sector":"قطاع",
            "search":'بحث',
            "createTask":"إنشاء مهمة",
            "createNew":"إنشاء الجديد",
             "vehicle":"مركبة",
            "placeofIssue":"مكان الإصدار",
            "plateNumber":"رقم لوحة",
            "plateCode":"رمز اللوحة",
            "chassisNumber":"رقم الهيكل",
            "cancel":"إلغاء",
            "establishmentName":"اسم المنشأة",
            "tradeLicense":"رخصة تجارية",
            "licenseSource":"مصدر الترخيص",
            "address":"عنوان",
            "establishmentDetails":"تفاصيل المنشأة",
            "licenseNumber":"رقم الرخصة",
            "licenseStartDate":"تاريخ بدء الترخيص",
            "licenseEndDate":"تاريخ انتهاء الترخيص",
            "arabicEstablishmentName":"اسم المنشأة باللغة العربية",
            "contactDetails":"بيانات التواصل",
            "emailid":" عنوات البريد الإلكتروني",
            "onHold":"تعليق",
            "businessActivity":"النشاط التجاري",
            "selectVehicle":"اختر السيارة",
            "selectBazar":"اختيار البازار",
            "taskType":"نوع المهمة",
            "createNewTask":"إنشاء مهمة جديدة",
            "createAndView":"إنشاء وعرض",
            "establishmentEngName":"اسم المنشأة بالإنجلزية",
            "establishmentArName":"اسم المنشأة بالعربية",
            "establishmentType":"نوع المنشأة",
            "establishmentClass":"فئة التأسيس",
            "plateCode":"رمز اللوحة",
            "plateNumber":"رقم لوحة",
            "vehicleMake":"اضافة مركبة",
            "contact":"بيانات التواصل",
            "tradeLicenseNumber":"رقم الرخصة التجارية",
            "tradeLicenseSource":"مصدر الرخصة التجارية",
            "createNewEstablishment":"إنشاء منشأة جديدة"    ,
            "bussinessActivitynotfound":"لم يتم العثور على قائمة الأنشطة الغذائية",
            "selectTaskType":"إختيار نوع المهمة"          
        },
        "serviceRequstList":{
            "serviceRequestList":"قائمة طلبات الخدمة",
            "serviceRequestNo":"رقم طلب الخدمة",
            "applicationType":"نوع الخدمة",
            "application":"الخدمة",  
            "serviceRequestDetails":"تفاصيل طلب الخدمة",
            "serviceRequestNo":"رقم طلب الخدمة", 
            "city":"مدينة",
            "status":"الحالة",
            "creationDate":"تاريخ الإنشاء",
            "closedDate":"تاريخ الإغلاق",
            "permitsStartDate":"تاريخ بدء التصريح",
            "permitEndDate":"تاريخ انتهاء التصريح",
            "businessActivity":"النشاط التجاري",  
            "category":"الفئة" ,
            "violationList":"قائمة المخالفات",
            "violationNumber":"رقم المخالفة",
            "inspectionNumber":"رقم التفتيش",
            "violationDetail":"تفاصيل المخالفة",
            "createdBy":"انشأ من قبل",       

        },
        "vehicleDetails":{
            "vehicleDetails":"تفاصيل السيارة",
            "plateCode":"رمز اللوحة",
            "plateNumber":"رقم لوحة",
            "placeOfIssue":"مكان الإصدار"
        },
	"closureInspection": {
            "title": "مهمة تفتيش الإغلاق الإداري",
            "tradeName": "اسم الرخصة التجارية",
            "licenseNo": "رقم الرخصة",
            "nameoffoodbusinessoperator": "اسم مسؤول المنشأة الغذائية",
            "signatureOfFood": "توقيع",
            "address": "عنوان",
            "comment": "تعليقات",
            "inspectorName": "اسم المفتش",
            "submit": "إرسال",
            "msg": "هل تمت الموافقة على هذا التفتيش?",
            "yes":"نعم",
            "no": "لا"
        },
        "campaignDetails": {
            "planNumber": "رقم الخطة",
            "comments": "الملاحظات",
             "planStartDate":"التاريخ المخطط للبدء",
            "expectedCompletionDate": "التاريخ المتوقع للإنجاز",
             "CompletionDate":"تاريخ الإنجاز",
            "priority": "الأولويات",
            "Description": "الوصف",
            "startCampaign": "تاريخ بدء الحملة",
            "campaignPlanDetails": "تفاصيل خطة الحملة",
            "listOfEstablishment": "قائمة المنشآت",
            "campaign":"حملة",
            "campaignInspection" : "تفتيش الحملات",
            "view" : "عرض"
        },
    }
}

export default Strings;