const shoppingList = {
    "InterfaceID": "ADFCA_CRM_SBL_007",
    "TimeStamp": "00:31:09",
    "LegalRepName": "",
    "InspectionCheckList": {
      "Inspection": {
        "OPADesc": "03/04/2021 13:36:53",
        "InspectorId": "ahmad.makki",
        "NearestDate": "2021-09-05",
        "InspectorName": "ahmad.makki",
        "LanguageType": "ENU",
        "GracePeriod": 0,
        "TaskId": "1-6387775248",
        "Thermometer": "N",
        "Flashlight": "N",
        "DataLogger": "N",
        "LuxMeter": "N",
        "UVLight": "N",
        "ActualInspectionDate": "03/04/2021 13:36:53",
        "ScorePercent": "100.00",
        "ContactName": "Abdul Rahman Midhlaj Mohammed",
        "MobileNumber": "0568084823",
        "EmiratesId": "784-1999-26361934",
        "Latitude": "24.4734185",
        "Longitude": "54.3770214",
        "Grade": "Grade A",
        "Comment": "",
        "Score": 264,
        "Action": "Satisfactory",
        "InspectionStatus": "Inspection Approved",
        "ListOfFsExpenseItem": {
          "Checklist": [
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "EFST program (certificate of success completion)",
              "ParameterNumber": "III-I",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "General structure including stairs ,lift cages and auxiliary structure",
              "ParameterNumber": "I-A1",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The wall surfaces and partitions",
              "ParameterNumber": "I-A10",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The ceiling",
              "ParameterNumber": "I-A11",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Windows and other openings",
              "ParameterNumber": "I-A12",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Doors",
              "ParameterNumber": "I-A13",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Working space",
              "ParameterNumber": "I-A14",
              "Regulation": "",
              "Score": 4
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Food separation",
              "ParameterNumber": "I-A15",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Building location and maintenance",
              "ParameterNumber": "I-A2",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Building  kept clean",
              "ParameterNumber": "I-A3",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Hand wash Basins &amp; facilities",
              "ParameterNumber": "I-A4",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Ventilation",
              "ParameterNumber": "I-A5",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Light protection and intensity",
              "ParameterNumber": "I-A6",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Drainage facilities",
              "ParameterNumber": "I-A7",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Staff toilets and changing facilities",
              "ParameterNumber": "I-A8",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The floor surfaces",
              "ParameterNumber": "I-A9",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "satisfactory",
              "DescriptionEnglish": "Equipments kept clean and disinfected",
              "ParameterNumber": "I-B1",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment design and material",
              "ParameterNumber": "I-B2",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment and serving utensils used at food display counters.",
              "ParameterNumber": "I-B4",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment maintenance &amp; calibration",
              "ParameterNumber": "I-B5",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Cleaning and disinfecting facilities.",
              "ParameterNumber": "I-B6",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Waste disposal  facilities",
              "ParameterNumber": "I-B7",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Hand washing",
              "ParameterNumber": "II-A2",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The personnel hygiene, uniform and protective clothing .",
              "ParameterNumber": "II-A3",
              "Regulation": "",
              "Score": 8
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Behaviors",
              "ParameterNumber": "II-A4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The food found protected from contamination through all stages of food chain and effective measures have been taken to prevent cross contamination.",
              "ParameterNumber": "II-B1",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Expired Food",
              "ParameterNumber": "II-B4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Food storage",
              "ParameterNumber": "II-B5",
              "Regulation": "",
              "Score": 8
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Raw materials, ingredients &amp; food source",
              "ParameterNumber": "II-B6",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Display of unpackaged &amp; ready to eat food",
              "ParameterNumber": "II-C2",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Packaging &amp; wrapping materials",
              "ParameterNumber": "II-C3",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "satisfactory",
              "DescriptionEnglish": "Food Washing facilities",
              "ParameterNumber": "II-C4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Pest  Control",
              "ParameterNumber": "II-C6",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "satisfactory",
              "DescriptionEnglish": "Chemicals usage &amp; storage",
              "ParameterNumber": "II-C7",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Cooking temperature",
              "ParameterNumber": "II-D3",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Storage temperature",
              "ParameterNumber": "II-D4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Thawing procedure.",
              "ParameterNumber": "II-D5",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Water and/or ice supply",
              "ParameterNumber": "II-E1",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Food transportation vehicle",
              "ParameterNumber": "II-F1",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Traceability &amp; Recall system (One step forward-one step back).",
              "ParameterNumber": "III-A",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "EFST program (Training Attendance Record)",
              "ParameterNumber": "III-B",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The food handler health status records",
              "ParameterNumber": "III-C",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Temp, cleaning, maintenance &amp; calibration records.",
              "ParameterNumber": "III-E",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "ADAFSA approvals/certificates and required  activities licensing  requirements",
              "ParameterNumber": "III-G",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "the officer -in -charge duties and responsibilities",
              "ParameterNumber": "III-H",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "تم التدريب وسيتم متابعة الاختبار في الزيارة القادمة",
              "DescriptionEnglish": "EFST program (certificate of success completion)",
              "ParameterNumber": "III-I",
              "Regulation": "",
              "Score": 8
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "General structure including stairs ,lift cages and auxiliary structure",
              "ParameterNumber": "I-A1",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The wall surfaces and partitions",
              "ParameterNumber": "I-A10",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The ceiling",
              "ParameterNumber": "I-A11",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Windows and other openings",
              "ParameterNumber": "I-A12",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Doors",
              "ParameterNumber": "I-A13",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Working space",
              "ParameterNumber": "I-A14",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Food separation",
              "ParameterNumber": "I-A15",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Building location and maintenance",
              "ParameterNumber": "I-A2",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Building  kept clean",
              "ParameterNumber": "I-A3",
              "Regulation": "",
              "Score": 4
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Hand wash Basins &amp; facilities",
              "ParameterNumber": "I-A4",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Ventilation",
              "ParameterNumber": "I-A5",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Light protection and intensity",
              "ParameterNumber": "I-A6",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Drainage facilities",
              "ParameterNumber": "I-A7",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Staff toilets and changing facilities",
              "ParameterNumber": "I-A8",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The floor surfaces",
              "ParameterNumber": "I-A9",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "satisfactory",
              "DescriptionEnglish": "Equipments kept clean and disinfected",
              "ParameterNumber": "I-B1",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment design and material",
              "ParameterNumber": "I-B2",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment and serving utensils used at food display counters.",
              "ParameterNumber": "I-B4",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment maintenance &amp; calibration",
              "ParameterNumber": "I-B5",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Cleaning and disinfecting facilities.",
              "ParameterNumber": "I-B6",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": 1,
              "DescriptionArabic": "",
              "GracePeriod": 7,
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "يمنع ترك حاوية النفايات مفتوحة",
              "DescriptionEnglish": "Waste disposal  facilities",
              "ParameterNumber": "I-B7",
              "Regulation": "",
              "Score": 1
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Hand washing",
              "ParameterNumber": "II-A2",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The personnel hygiene, uniform and protective clothing .",
              "ParameterNumber": "II-A3",
              "Regulation": "",
              "Score": 8
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Behaviors",
              "ParameterNumber": "II-A4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The food found protected from contamination through all stages of food chain and effective measures have been taken to prevent cross contamination.",
              "ParameterNumber": "II-B1",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Expired Food",
              "ParameterNumber": "II-B4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Food storage",
              "ParameterNumber": "II-B5",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Raw materials, ingredients &amp; food source",
              "ParameterNumber": "II-B6",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Halal &amp; non-Halal separation",
              "ParameterNumber": "II-B7",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Display of unpackaged &amp; ready to eat food",
              "ParameterNumber": "II-C2",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Packaging &amp; wrapping materials",
              "ParameterNumber": "II-C3",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "satisfactory",
              "DescriptionEnglish": "Food Washing facilities",
              "ParameterNumber": "II-C4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Pest  Control",
              "ParameterNumber": "II-C6",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "satisfactory",
              "DescriptionEnglish": "Chemicals usage &amp; storage",
              "ParameterNumber": "II-C7",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Cooking temperature",
              "ParameterNumber": "II-D3",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Storage temperature",
              "ParameterNumber": "II-D4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Thawing procedure.",
              "ParameterNumber": "II-D5",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Water and/or ice supply",
              "ParameterNumber": "II-E1",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Traceability &amp; Recall system (One step forward-one step back).",
              "ParameterNumber": "III-A",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "EFST program (Training Attendance Record)",
              "ParameterNumber": "III-B",
              "Regulation": "",
              "Score": 8
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The food handler health status records",
              "ParameterNumber": "III-C",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Temp, cleaning, maintenance &amp; calibration records.",
              "ParameterNumber": "III-E",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": 0,
              "DescriptionArabic": "",
              "GracePeriod": 7,
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "رصد عدم الإلتزام بالنشاط المرخص له ألا وهو بيع الوجبات الخفيفه ( كافيتيريا ) وهو يقوم بنشاط مطعم",
              "DescriptionEnglish": "ADAFSA approvals/certificates and required  activities licensing  requirements",
              "ParameterNumber": "III-G",
              "Regulation": "",
              "Score": 0
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "the officer -in -charge duties and responsibilities",
              "ParameterNumber": "III-H",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "General structure including stairs ,lift cages and auxiliary structure",
              "ParameterNumber": "I-A1",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The wall surfaces and partitions",
              "ParameterNumber": "I-A10",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The ceiling",
              "ParameterNumber": "I-A11",
              "Regulation": "",
              "Score": 4
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Windows and other openings",
              "ParameterNumber": "I-A12",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Doors",
              "ParameterNumber": "I-A13",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Working space",
              "ParameterNumber": "I-A14",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Food separation",
              "ParameterNumber": "I-A15",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Building location and maintenance",
              "ParameterNumber": "I-A2",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Building  kept clean",
              "ParameterNumber": "I-A3",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Hand wash Basins &amp; facilities",
              "ParameterNumber": "I-A4",
              "Regulation": "",
              "Score": 4
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Ventilation",
              "ParameterNumber": "I-A5",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Light protection and intensity",
              "ParameterNumber": "I-A6",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Drainage facilities",
              "ParameterNumber": "I-A7",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Staff toilets and changing facilities",
              "ParameterNumber": "I-A8",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The floor surfaces",
              "ParameterNumber": "I-A9",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipments kept clean and disinfected",
              "ParameterNumber": "I-B1",
              "Regulation": "",
              "Score": 4
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment design and material",
              "ParameterNumber": "I-B2",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment and serving utensils used at food display counters.",
              "ParameterNumber": "I-B4",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Equipment maintenance &amp; calibration",
              "ParameterNumber": "I-B5",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Cleaning and disinfecting facilities.",
              "ParameterNumber": "I-B6",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART I : Design, Structure and Equipment",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Waste disposal  facilities",
              "ParameterNumber": "I-B7",
              "Regulation": "",
              "Score": 4
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Hand washing",
              "ParameterNumber": "II-A2",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The personnel hygiene, uniform and protective clothing .",
              "ParameterNumber": "II-A3",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers:II-A: Food handler(health &amp; personal hygiene)",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Behaviors",
              "ParameterNumber": "II-A4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The food found protected from contamination through all stages of food chain and effective measures have been taken to prevent cross contamination.",
              "ParameterNumber": "II-B1",
              "Regulation": "",
              "Score": 8
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Expired Food",
              "ParameterNumber": "II-B4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Food storage",
              "ParameterNumber": "II-B5",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Raw materials, ingredients &amp; food source",
              "ParameterNumber": "II-B6",
              "Regulation": "",
              "Score": 8
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Halal &amp; non-Halal separation",
              "ParameterNumber": "II-B7",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Display of unpackaged &amp; ready to eat food",
              "ParameterNumber": "II-C2",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Packaging &amp; wrapping materials",
              "ParameterNumber": "II-C3",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "satisfactory",
              "DescriptionEnglish": "Food Washing facilities",
              "ParameterNumber": "II-C4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Pest  Control",
              "ParameterNumber": "II-C6",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "satisfactory",
              "DescriptionEnglish": "Chemicals usage &amp; storage",
              "ParameterNumber": "II-C7",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Cooking temperature",
              "ParameterNumber": "II-D3",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Storage temperature",
              "ParameterNumber": "II-D4",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Thawing procedure.",
              "ParameterNumber": "II-D5",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART II: Hygiene Practices &amp; Food Handlers",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Water and/or ice supply",
              "ParameterNumber": "II-E1",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Traceability &amp; Recall system (One step forward-one step back).",
              "ParameterNumber": "III-A",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "EFST program (Training Attendance Record)",
              "ParameterNumber": "III-B",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "The food handler health status records",
              "ParameterNumber": "III-C",
              "Regulation": "",
              "Score": "8"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "Temp, cleaning, maintenance &amp; calibration records.",
              "ParameterNumber": "III-E",
              "Regulation": "",
              "Score": 4
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "ADAFSA approvals/certificates and required  activities licensing  requirements",
              "ParameterNumber": "III-G",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "1",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "the officer -in -charge duties and responsibilities",
              "ParameterNumber": "III-H",
              "Regulation": "",
              "Score": "4"
            },
            {
              "GracePeriodDate": "",
              "Answers": "4",
              "DescriptionArabic": "",
              "GracePeriod": "",
              "QuestionNameArabic": "",
              "QuestionNameEnglish": "PART III: Documentation &amp; Records",
              "Weightage": "2",
              "NonComplianceEnglish": "",
              "NonComplianceArabic": "",
              "NA": false,
              "Action": "",
              "NI": "N",
              "Comments": "Satisfactory",
              "DescriptionEnglish": "EFST program (certificate of success completion)",
              "ParameterNumber": "III-I",
              "Regulation": "",
              "Score": "8"
            }
          ]
        }
      }
    },
    "IsReschedule": ""
  };
  
  describe('scoreCalculation', () => {
    test('the grade for satisfactory checklist array', () => {
        let checkList = shoppingList.InspectionCheckList.Inspection.ListOfFsExpenseItem.Checklist
      for (let b = 1; b < checkList.length; b++) {
          let element = checkList[b];
          expect(element.Answers).not.toBe(3)
        }
    
    });
  })

